development:
  adapter: async

test:
  adapter: async

staging:
  adapter: redis
  url: <%= ENV["REDIS_URL"] %>
  channel_prefix: syosset_staging

production:
  adapter: redis
  url: <%= ENV["REDIS_URL"] %>
  channel_prefix: syosset_production
