production:
  clients:
    default:
      uri: <%= ENV['MONGO_URL'] || ENV['MONGODB_URI'] %>
staging:
  clients:
    default:
      uri: <%= ENV['MONGO_URL'] || ENV['MONGODB_URI'] %>
development:
  clients:
    default:
      database: syosset_development
      hosts:
        - 127.0.0.1:27017